import matplotlib

matplotlib.use('Agg')

from enabol.history import FitHistory


def write_trace(path, trace, metric, values):
    rows = [
        '# ----',
        f'# Trace: {trace}',
        '# Generated by enabol+hls4ml-trainable',
        '# ENABOL version: 0.1.0',
        '# hls4ml-trainable version: 0.0.0a',
        '# User: manuelbv',
        '# Host: kona-ubuntu',
        '# Date: 2026-05-23 14:15:11',
        '# Project: LinearBlockModel',
        '# Backend: Vitis',
        '# Controller: CTRL-NONE',
        '# Optimizer: sgd',
        '# LearningRate: 0.01',
        '# Loss: half_mse',
        '# BatchSize: 1',
        '# Epochs: 2',
        '# Shuffle: true',
        '# ShuffleSeed: 13',
        '# LogEvery: 10',
        '# ---',
        f'epoch,sample,global_step,sample_index,{metric}',
    ]
    for global_step, value in enumerate(values):
        epoch = 1 + global_step // 2
        sample = 1 + global_step % 2
        sample_index = global_step % 2
        rows.append(f'{epoch},{sample},{global_step},{sample_index},{value}')
    path.write_text('\n'.join(rows) + '\n')


def test_fit_history_loads_trainable_traces(tmp_path):
    trace_dir = tmp_path / 'tb_data' / 'training'
    trace_dir.mkdir(parents=True)
    write_trace(trace_dir / 'loss.dat', 'loss', 'loss', [1.0, 0.5, 0.25, 0.125])
    write_trace(trace_dir / 'alpha.dat', 'alpha', 'alpha', [1.0, 1.0, 1.0, 1.0])

    history = FitHistory.from_dir(tmp_path)

    assert history.frame is not None
    assert list(history.frame.columns) == ['alpha', 'loss']
    assert history.frame.index.names == ['epoch', 'sample', 'global_step', 'sample_index']
    assert history.metadata['Project'] == 'LinearBlockModel'
    assert history.metadata_by_trace['loss']['Controller'] == 'CTRL-NONE'
    assert history['loss'].shape == (4,)


def test_fit_history_plot_training_returns_figure(tmp_path):
    trace_dir = tmp_path / 'tb_data' / 'training'
    trace_dir.mkdir(parents=True)
    write_trace(trace_dir / 'loss.dat', 'loss', 'loss', [1.0, 0.5, 0.25, 0.125])
    write_trace(trace_dir / 'alpha.dat', 'alpha', 'alpha', [1.0, 1.0, 1.0, 1.0])

    history = FitHistory.from_trainable_dir(trace_dir)
    fig, axes = history.plot_training(window_size=2, show=False)

    assert fig is not None
    assert len(axes) == 2
