import matplotlib

matplotlib.use('Agg')

from enabol.history import FitHistory
from enabol.testbench import TestbenchData


def write_trace(path, trace, metric, values, *, every=1):
    rows = [
        '# ----',
        f'# Trace: {trace}',
        '# Generated by enabol+hls4ml-trainable',
        '# ENABOL version: 0.1.0',
        '# hls4ml-trainable version: 0.0.0a',
        '# User: manuelbv',
        '# Host: kona-ubuntu',
        '# Date: 2026-05-23 14:15:11',
        '# Project: LinearBlockModel',
        '# Backend: Vitis',
        '# Controller: CTRL-NONE',
        '# Optimizer: sgd',
        '# LearningRate: 0.01',
        '# Loss: half_mse',
        '# BatchSize: 1',
        '# Epochs: 2',
        '# Shuffle: true',
        '# ShuffleSeed: 13',
        '# LogEvery: 10',
        '# ---',
        f'epoch,sample,global_step,sample_index,{metric}',
    ]
    for row_index, value in enumerate(values):
        global_step = row_index * every
        epoch = 1 + global_step // 2
        sample = 1 + global_step % 2
        sample_index = global_step % 2
        rows.append(f'{epoch},{sample},{global_step},{sample_index},{value}')
    path.write_text('\n'.join(rows) + '\n')


def write_controller_trace(path):
    rows = [
        '# ----',
        '# Trace: controller',
        '# Generated by enabol+hls4ml-trainable',
        '# Project: LinearBlockModel',
        '# Controller: CTRL-GT-ORDER-1',
        '# ---',
        'epoch,sample,global_step,sample_index,dtheta_sq,dgrad_sq,lhs_sq,rhs_sq,alpha_feasible,alpha_state',
        '1,1,0,0,0.0,0.0,0.0,0.0,1.0,1.0',
        '1,2,1,1,0.25,0.5,0.00005,0.5625,0.875,0.9875',
    ]
    path.write_text('\n'.join(rows) + '\n')


def test_fit_history_stays_software_training_container():
    history = FitHistory(loss=[1, 2, 3])

    assert 'loss' in history
    assert not hasattr(history, 'from_dir')


def test_testbench_data_loads_trainable_traces(tmp_path):
    trace_dir = tmp_path / 'tb_data' / 'training'
    trace_dir.mkdir(parents=True)
    write_trace(trace_dir / 'loss.dat', 'loss', 'loss', [1.0, 0.5, 0.25, 0.125])
    write_trace(trace_dir / 'alpha.dat', 'alpha', 'alpha', [1.0, 1.0, 1.0, 1.0])

    data = TestbenchData.from_dir(tmp_path)

    assert list(data.frame.columns) == ['alpha', 'loss']
    assert data.frame.index.names == ['epoch', 'sample', 'global_step', 'sample_index']
    assert data.metadata['Project'] == 'LinearBlockModel'
    assert data.metadata_by_trace['loss']['Controller'] == 'CTRL-NONE'
    assert data['loss'].shape == (4,)
    assert data.metrics == ['alpha', 'loss']
    assert 'TestbenchData' in repr(data)
    assert 'loss' in repr(data)


def test_testbench_data_plot_training_returns_figure(tmp_path):
    trace_dir = tmp_path / 'tb_data' / 'training'
    trace_dir.mkdir(parents=True)
    write_trace(trace_dir / 'loss.dat', 'loss', 'loss', [1.0, 0.5, 0.25, 0.125])
    write_trace(trace_dir / 'alpha.dat', 'alpha', 'alpha', [1.0, 1.0, 1.0, 1.0])

    data = TestbenchData.from_trainable_dir(trace_dir)
    fig, axes = data.plot_training(window_size=2, show=False)

    assert fig is not None
    assert len(axes) == 2


def test_testbench_data_loads_controller_trace_as_top_level_scalars(tmp_path):
    trace_dir = tmp_path / 'tb_data' / 'training'
    trace_dir.mkdir(parents=True)
    write_trace(trace_dir / 'loss.dat', 'loss', 'loss', [1.0, 0.5])
    write_trace(trace_dir / 'alpha.dat', 'alpha', 'alpha', [1.0, 0.9875])
    write_controller_trace(trace_dir / 'controller.dat')

    data = TestbenchData.from_dir(tmp_path)
    fig, axes = data.plot_training(metrics=['loss', 'alpha', 'dtheta_sq', 'alpha_state'], window_size=1, show=False)

    assert 'controller' in data.metadata_by_trace
    assert 'dtheta_sq' in data.frame.columns
    assert 'alpha_state' in data.scalar_metrics
    assert data.frame['alpha_feasible'].iloc[-1] == 0.875
    assert fig is not None
    assert len(axes) == 4


def test_testbench_data_handles_sparse_trace_cadences(tmp_path):
    trace_dir = tmp_path / 'tb_data' / 'training'
    trace_dir.mkdir(parents=True)
    layer_dir = trace_dir / 'dense0'
    layer_dir.mkdir()
    write_trace(trace_dir / 'loss.dat', 'loss', 'loss', [1.0, 0.5, 0.25, 0.125])
    write_trace(layer_dir / 'weights.dat', 'dense0/weights', 'weight_0_0', [0.25, 0.125], every=2)
    write_trace(layer_dir / 'biases.dat', 'dense0/biases', 'bias_0', [0.0, 0.125], every=2)

    data = TestbenchData.from_dir(tmp_path)
    fig, axes = data.plot_training(metrics=['loss', 'dense0.weights.mean', 'dense0.biases.mean'], window_size=2, show=False)

    assert data.metadata_by_trace['dense0/weights']['_path'] == 'dense0/weights.dat'
    assert 'dense0' in data.layers
    assert data.layers['dense0'].weights['weight_0_0'].notna().sum() == 2
    assert data.layers['dense0'].biases['bias_0'].notna().sum() == 2
    assert 'dense0.weights.mean' in data.stats_frame.columns
    assert 'dense0.biases.mean' in data.scalar_metrics
    assert 'dense0.weights.weight_0_0' not in data.frame.columns
    assert fig is not None
    assert len(axes) == 3


def test_testbench_data_can_skip_or_select_parameter_layers(tmp_path):
    trace_dir = tmp_path / 'tb_data' / 'training'
    trace_dir.mkdir(parents=True)
    dense0_dir = trace_dir / 'dense0'
    dense1_dir = trace_dir / 'dense1'
    dense0_dir.mkdir()
    dense1_dir.mkdir()
    write_trace(trace_dir / 'loss.dat', 'loss', 'loss', [1.0])
    write_trace(dense0_dir / 'weights.dat', 'dense0/weights', 'weight_0_0', [0.25])
    write_trace(dense1_dir / 'weights.dat', 'dense1/weights', 'weight_0_0', [0.5])

    no_weights = TestbenchData.from_dir(tmp_path, load_weights=False)
    only_dense1 = TestbenchData.from_dir(tmp_path, load_weights=['dense1'])

    assert no_weights.layers == {}
    assert list(no_weights.frame.columns) == ['loss']
    assert list(only_dense1.layers) == ['dense1']
    assert 'dense1.weights.mean' in only_dense1.stats_frame.columns
